### ISSUE TITLE
Failed to build documentation

### ISSUE THREAD

**Issue by JoseGuzman** [neurodroid/stimfit#24]
When  running in $STIMFITHOME/doc/sphinx/ the following command line:
$> sphinx-build ./ ~/tmp/stf/doc

I've got the following error

Running Sphinx v1.1.3
loading pickled environment... done
No builder selected, using default: html

Theme error:
no theme named 'alabaster' found (missing theme.conf?)

Note in that branch 0.14 this command works.

**Comment by neurodroid** [comment]
You can get it from pip, e.g.
`sudo pip-3.4 install alabaster`
or whatever version of pip you want to use

**Comment by JoseGuzman** [comment]
the following line should be added to conf.py

html_theme_path = ["/usr/local/lib/python2.7/dist-packages/"]

I will submit a pull request as soon as I learn how to do it :+1:

**Comment by neurodroid** [comment]
I don't think this should be added as it will look different depending on which platform and which Python version you use. I don't have a single system where this path would be correct.

**Comment by JoseGuzman** [comment]
I think the easiest way to go with this is suggested in Pull request #25. Alternativerly, in the future, we may include a custom-made theme within the repository.

**Comment by neurodroid** [comment]
OK, merged #25, closing this issue. Thanks for your pr.
