### ISSUE TITLE
Problem unselecting false-positive traces in MacOS X 10.10.5

### ISSUE THREAD

**Issue by fjohenning** [neurodroid/stimfit#29]
Hi,
working with my data, I encountered another problem: When I have the events detected and want to go through the single events in the edit mode, I can add new events (false negatives), but clicking the checkboxes next to the arrows, it is not possible to get rid of the false positives as indicated in the manual.
Best regards
Friedrich

**Comment by neurodroid** [comment]
Fixed in 0.14.13, pending upload to MacPorts (https://trac.macports.org/ticket/49914)

**Comment by neurodroid** [comment]
@fjohenning An updated version should now be available via MacPorts:
```bash
sudo port selfupdate
sudo port upgrade -u outdated
```
Let me know if this works for you so that we can close this issue

**Comment by fjohenning** [comment]
Thank you very much!
The update works great.
