### ISSUE TITLE
Trace scaling fails

### ISSUE THREAD

**Issue by athasd** [neurodroid/stimfit#43]
Hi,

we are using stimfit 0.15.2 in a debian machine installed through neurodebian. Everything works well when opening a file (Heka), but after event detection or concatenation of selected sweeps, the trace scaling keys (+, -, ctrl +, ctrl -, f) are not working anymore. 

Any clue about what could be the problem?

thank you in advanced!

**Comment by schloegl** [comment]
I tested this with recent version (0.16.4) of stimfit, on Linux, and with stimfit-lite on windows, and I can not reproduce the problem. Please upgrade and let us know if the problem is not solved.
