### ISSUE TITLE
Stimfit Hang issues while expanding Y scale

### ISSUE THREAD

**Issue by zubinrashid** [neurodroid/stimfit#57]
Hello
I am having issues with opening  files which previously used to open pretty fine in StimFit. THey still have data in them which I can see when opening them in Patchmaster. Everytime I am expanding the Y scale it is getting petrified. Please help me with this. Its urgent

**Comment by neurodroid** [comment]
Hi,

Which operating system are you on?

C

**Comment by schloegl** [comment]
I can not reproduce the issue with the latest version of stimfit. Assuming this is solved.
