### ISSUE TITLE
Building Win64 versions with VC++ 2008 Express

### ISSUE THREAD

**Issue by kh90909** [neurodroid/stimfit#8]
I have succeeding in building a 64-bit version of the python stfio module using VC++ 2008 Express. I'm creating this issue to document how I did this. Hopefully you can review and test this and consider including the code in stimfit. If this is not feasible, feel free to close this issue. I won't be offended! 

The changes necessary can be found in the [win64 branch] (https://github.com/kh90909/stimfit/tree/win64) of my fork. The main change is setting up VC++ 2008 Express to build 64-bit targets, documented in [prerequisites.rst] (https://github.com/kh90909/stimfit/tree/win64/doc/sphinx/win_install_guide/prerequisites.rst) and [VCExpress64bitsetup.rst] (https://github.com/kh90909/stimfit/tree/win64/doc/sphinx/win_install_guide/VCExpress64bitsetup.rst). Beyond this, the only changes were to add x64 configurations to the `.vcproj` files and download 64-bit versions of the dependencies. (There is nothing special in the changes to the `.vcproj` files. I generated these changes simply by editing the Stimfit.sln configuration in Visual Studio and adding an x64 configuration with all the default settings). 

I had to make one reversion (kh90909/stimfit@cbd9ec9) to biosiglib.cpp because I had to use Biosig 1.5.6. For some reason, later Windows releases of Biosig do not include DLLs. It seems more like a bug in a build script rather than an intentional omission. I [raised] (http://sourceforge.net/p/biosig/mailman/message/33039296/) this issue on their mailing list, but they seem focused on building with MXE.
 
I'm not submitting this as a pull request at this point because it needs further testing, which unfortunately I don't have time to do:

* Does this build work on a 32-bit Windows host (it should)?
* Do the changes break anything when building Win32 versions (they shouldn't)?
* Will the rest of Stimfit build successfully? I've only built pystfio, but I'm hopeful the rest of the build will work without any further changes other than getting 64-bit versions of the other dependencies.

Feel free to pull in changes from my repo as appropriate. If you'd like me to submit a pull request, just let me know.

**Comment by neurodroid** [comment]
Thanks again for putting together these instructions. They've been very helpful to build the first 64-bit version of stimfit:
https://github.com/neurodroid/stimfit/releases/tag/v0.14.1windows
I've also updated the build instructions to make everything 64-bit:
http://www.stimfit.org/doc/sphinx/win_install_guide/prerequisites.html
Maybe that's helpful for Conda as well.

**Comment by kh90909** [comment]
Glad I could help. Yes, the libbiosig builds you're providing will simplify things for the conda packages. I'm a bit busy at the moment, but will update the package recipes to use these when I have a chance.

I guess I can close this issue now that this is done. Feel free to reopen for further discussion if necessary.

**Comment by neurodroid** [comment]
Just to let you know that branch 0.14 has been merged into the master branch. 0.14 is now obsolete (though I'll try to keep it synced with master until we switch to 0.15).
