### ISSUE TITLE
Missing labels on scale bar

### ISSUE THREAD

**Issue by Sverreg** [neurodroid/stimfit#89]
The labels on the scale bar are missing in stimfit 0.16.0, on Ubuntu 20.04 (unless there is a way to toggle labels that I can't find).

![image](https://user-images.githubusercontent.com/27206049/130357904-c123634f-726e-4303-9579-6ce3ff99b501.png)

This might be related to the errors I get when I run stimfit, from[ Issue #79 ](https://github.com/neurodroid/stimfit/issues/79#issuecomment-901766763)

![image](https://user-images.githubusercontent.com/27206049/130358001-7943ce62-7666-470c-9bde-0b53110ab35a.png)

**Comment by neurodroid** [comment]
Might have something to do with dark mode, fonts might be white in dark mode.

**Comment by neurodroid** [comment]
@Sverreg Can you check the box for the second channel ("Show reference") in the top left box, and test whether the scale bar labels are printed in red for the second channel? That would tell us whether the problem lies with the dark mode.

**Comment by Sverreg** [comment]
> Might have something to do with dark mode, fonts might be white in dark mode.

Ahh, you are right. Changing Ubuntu to Light or Standard mode immediately reveals the labels on the scale bar. 




> @Sverreg Can you check the box for the second channel ("Show reference") in the top left box, and test whether the scale bar labels are printed in red for the second channel? That would tell us whether the problem lies with the dark mode.

The red labels for the second channel are visible in Dark, Light and Standard mode Ubuntu. 

Thanks!
