### ISSUE TITLE
Accessing template matching from the pythong shell

### ISSUE THREAD

**Issue by GyulaMaloveczky** [neurodroid/stimfit#96]
Can I use Correlation coefficient template matching from the pyhton shell? I can't seem to find in any documentation about what the "stf.detect_event" function's "mode" parameter can be besides criterion.
Thank you for the help!

**Comment by neurodroid** [comment]
This is indeed undocumented.

The available modes are “criterion”, “correlation”, and “deconvolution”.

See
https://github.com/neurodroid/stimfit/blob/master/src/pystfio/pystfio.cxx#L140
